events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('', views.event_list, name='event_list'),              
    path('host/', views.host_dashboard, name='host_dashboard'), 
    path('new/', views.event_create, name='event_create'),     
    path('<int:event_id>/edit/', views.event_edit, name='event_edit'),
    path('<int:event_id>/delete/', views.event_delete, name='event_delete'),
    path('<int:event_id>/', views.event_detail, name='event_detail'),
    path('<int:event_id>/guests/', views.event_guests, name='event_guests'),
    path('<int:event_id>/guests/<int:guest_id>/delete/', views.guest_delete, name='guest_delete'),
    path("signup/", views.signup, name="signup"),
]

rsvp/urls.py
from django.urls import path
from . import views

app_name = "rsvp"

urlpatterns = [
    path('', views.rsvp_home, name='rsvp'),
    path('about/', views.about, name='about'),    
    path('contact/', views.contact, name='contact'),
    path('confirm/<int:event_id>/', views.rsvp_confirm, name='rsvp_confirm'),
]

weddingrsvp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from events.views import event_list
from rsvp.views import rsvp_home , home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('weddingrsvp/', rsvp_home, name='weddingrsvp'),
    path('events/', include('events.urls')),
    path('rsvp/', include('rsvp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
    <link rel="stylesheet" href="{% static 'css/section.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <title>
        {% block title %}
        {% endblock title%}
    </title>
    
</head>

<body>
<header class="center">

        <nav>
            <input type="checkbox" id="nav-check">

            <div class="nav-btn">
                <label for="nav-check">
                    <span></span>
                    <span></span>
                    <span></span>
                </label>
            </div>

           
            <div class="nav-link center">
                <h2>Yay or Nay RSVP</h2>
                <a href="{% url 'home' %}">Home</a>
                <a href="{% url 'rsvp:about' %}">About</a>
                <a href="{% url 'events:event_list' %}">Events</a>  
                <a href="{% url 'rsvp:contact' %}">Contact</a>    

            {% if user.is_authenticated %}
                <a href="{% url 'events:host_dashboard' %}">Host Dashboard</a>
                <form method="post" action="{% url 'logout' %}" class="logout-form">
            {% csrf_token %}
                <button type="submit" class="logout-link">Log Out</button>
                </form>
            {% else %}
                <a href="{% url 'login' %}">Log In</a>
                <a href="{% url 'events:signup' %}">Register</a>
            {% endif %}
            </div>

        </nav>

    </header>
    <main>


        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <a href="">
            <h2>Yay or Nay RSVP</h2>
        </a>

        <nav class="nav-footer center">
                <a href="{% url 'home' %}">Home</a>
                <a href="{% url 'rsvp:about' %}">About</a>
                <a href="{% url 'events:event_list' %}">Events</a>  
                <a href="{% url 'rsvp:contact' %}">Contact</a>   
        </nav>

    </footer>
</body>

</html>